# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_key', models.CharField(max_length=64, unique=True, verbose_name='Chave')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Valor')),
                ('status_code', models.IntegerField(blank=True, db_index=True, null=True, verbose_name=b'C\xc3\xb3digo de retorno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Nome do Provedor')),
                ('status', models.BooleanField(default=1, verbose_name=b'Status')),
            ],
            options={
                'verbose_name': 'Provedor de pagamento',
                'verbose_name_plural': 'Provedores de pagamento',
            },
        ),
        migrations.CreateModel(
            name='TargetProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentProvider')),
            ],
            options={
                'verbose_name': 'Provedor Default',
                'verbose_name_plural': 'Provedores Default',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentProvider'),
        ),
    ]
