# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='slug',
            field=models.SlugField(default='', verbose_name=b'Slug'),
            preserve_default=False,
        ),
    ]
