# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentprovider_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos Realizados'},
        ),
        migrations.AlterModelOptions(
            name='targetprovider',
            options={'verbose_name': 'Chavear Provedor', 'verbose_name_plural': 'Chavear Provedor'},
        ),
        migrations.AddField(
            model_name='targetprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 4, 16, 50, 19, 815738, tzinfo=utc), verbose_name=b'Atualizado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Gerado em'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='status',
            field=models.BooleanField(default=1, verbose_name=b'Ativo?'),
        ),
    ]
