# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20160504_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='response_text',
            field=models.TextField(blank=True, null=True, verbose_name=b'Resposta do provedor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name=b'Chave de pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentProvider', verbose_name=b'Provedor'),
        ),
    ]
