# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20160504_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code_pagseguro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'C\xc3\xb3digo Pagseguro'),
        ),
        migrations.AlterField(
            model_name='targetprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentProvider', verbose_name=b'Provedor'),
        ),
    ]
