# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20160505_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='code_pagseguro',
            new_name='pagseguro_code',
        ),
        migrations.AddField(
            model_name='payment',
            name='pagseguro_url',
            field=models.URLField(blank=True, null=True, verbose_name=b'URL Pagseguro'),
        ),
    ]
