# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20160505_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='numautor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'N\xc3\xbamero Autoriza\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AddField(
            model_name='payment',
            name='numcv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Comprovante de vendas'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_type',
            field=models.CharField(choices=[(b'visa', b'Visa'), (b'mastercard', b'Mastercard'), (b'diners', b'Diners'), (b'discover', b'Discover'), (b'elo', b'Elo'), (b'amex', b'Amex'), (b'JCB', b'JCB'), (b'Aura', b'Aura')], max_length=30, verbose_name=b'Bandeira'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_code',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name=b'Cod'),
        ),
    ]
