# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20160522_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Transa\xc3\xa7\xc3\xa3o ID Cielo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='numautor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'N\xc3\xbamero Autoriza\xc3\xa7\xc3\xa3o Rede'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='numcv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Comprovante de vendas Rede'),
        ),
    ]
