# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20160522_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.SlugField(blank=True, null=True, verbose_name=b'Projeto'),
        ),
    ]
