# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20160522_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='company_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'C\xc3\xb3digo do Estabelecimento'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='company_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Chave'),
        ),
    ]
