# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20160802_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='company_code_test',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'C\xc3\xb3digo (homologa\xc3\xa7\xc3\xa3o)'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='company_key_test',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Chave (homologa\xc3\xa7\xc3\xa3o)'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='company_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'C\xc3\xb3digo'),
        ),
    ]
